version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: lixylearning-frontend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
  backend:
    build: ./backend
    container_name: lixylearning-backend
    ports:
      - "5001:5000"
    env_file:
      - .env
    restart: always

  postgres:
    build: ./db
    container_name: lixylearning-postgres-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
