name: Deploy Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push Docker image
        uses: docker/build-push-action@v4
        with: 
          context: .
          push: true
          tags: marioarellano/lexilearn-frontend:latest
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          REACT_APP_BACKEND_HOST: ${{ vars.REACT_APP_BACKEND_HOST }}

