-- Memes category + viral-phrase vocabulary (for DBs already seeded without Memes).
-- Safe to run once; re-run skips existing rows by vocabulary_id.

INSERT INTO categories (category_name)
SELECT 'Memes'
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE LOWER(TRIM(category_name)) = 'memes');

INSERT INTO vocabulary (vocabulary_id, word, type, cefr, definition, example, category_id, image_url)
VALUES
(5700, 'touch grass', 'phrase', 'b2', 'Internet slang: telling someone to go outside, disconnect from online drama, and engage with the real world. Often humorous or dismissive.', 'You have been arguing for hours—touch grass.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80'),
(5701, 'no cap', 'phrase', 'b2', 'Slang meaning “no lie” or “seriously”; used to stress that you are telling the truth.', 'That concert was the best I have ever seen, no cap.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1588850561407-ed78c204e0d1?auto=format&fit=crop&w=800&q=80'),
(5702, 'main character energy', 'phrase', 'b2', 'Acting as if you are the protagonist of a story—confident, dramatic, or self-focused in a playful or critical way.', 'She walked in late in sunglasses—total main character energy.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1503095396549-807759242b92?auto=format&fit=crop&w=800&q=80'),
(5703, 'it''s giving', 'phrase', 'b2', 'Short for “it’s giving…”: says something strongly resembles a vibe, era, or stereotype (often ironic).', 'This playlist—it''s giving 2000s sleepover.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1557683316-973673baf926?auto=format&fit=crop&w=800&q=80'),
(5704, 'slay', 'verb', 'b2', 'Slang: to do something exceptionally well; praise for style, performance, or confidence.', 'You slayed that presentation.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=800&q=80'),
(5705, 'rent free', 'phrase', 'b2', 'Living “rent free” in someone’s head: occupying their thoughts without effort (often mocking obsession).', 'Why is he still tweeting about you? You live rent free in his head.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80'),
(5706, 'say less', 'phrase', 'b2', 'Informal: “I understand—no need to explain more”; agreement or readiness to act.', 'Want pizza? Say less.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80'),
(5707, 'this you', 'phrase', 'b2', 'Used to call out hypocrisy: “Is this you?” often paired with evidence of contradictory behavior.', 'You said you hate drama—this you starting the group chat?', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=800&q=80'),
(5708, 'caught in 4K', 'phrase', 'b2', 'Caught with clear, undeniable proof—like ultra-HD evidence of a mistake or lie (often humorous).', 'He said he was home early—then the story tag caught him in 4K.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80'),
(5709, 'based', 'adjective', 'b2', 'Internet slang: praise for being authentic, unapologetic, or holding an unconventional opinion confidently.', 'She said exactly what everyone was thinking—based.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80'),
(5710, 'cringe', 'adjective', 'b2', 'Second-hand embarrassment; awkward content or behavior that makes viewers uncomfortable.', 'That forced apology video was pure cringe.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80'),
(5711, 'go off', 'phrase', 'b2', 'Encourage someone to continue (often a rant or performance); can mean “get angry” in other contexts.', 'She spilled every detail—go off, queen.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=800&q=80'),
(5712, 'sending me', 'phrase', 'b2', 'Something is so funny it “sends” you—i.e. you cannot stop laughing.', 'That typo in the email is sending me.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80'),
(5713, 'NPC behavior', 'phrase', 'b2', 'Acting like a non-player character: mindless, robotic, or lacking critical thought (internet critique).', 'He just repeats talking points—NPC behavior.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80'),
(5714, 'understood the assignment', 'phrase', 'b2', 'Did something perfectly on-theme; exceeded expectations for the situation.', 'Her costume was detailed—she understood the assignment.', (SELECT category_id FROM categories WHERE LOWER(TRIM(category_name)) = 'memes' LIMIT 1), 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80')
ON CONFLICT (vocabulary_id) DO NOTHING;
