name: CI/CD Pipeline with Branch Restrictions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  restrict:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "Pull requests to main are only allowed from develop."
          exit 1

  build-frontend:
    runs-on: ubuntu-latest
    needs: restrict  # Ensure this runs only if restrict job passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build the app
        run: |
          cd frontend
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: marioarellano/lixylearning-frontend:latest
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=${{ vars.NEXT_PUBLIC_BACKEND_URL }}

  build-backend:
    runs-on: ubuntu-latest
    needs: restrict  # Ensure this runs only if restrict job passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: marioarellano/lixylearning-backend:latest
          build-args: |
            NEXT_PUBLIC_FRONTEND_URLS=${{ vars.NEXT_PUBLIC_FRONTEND_URLS }}

  build-postgres:
    runs-on: ubuntu-latest
    needs: restrict  # Ensure this runs only if restrict job passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push postgres
        uses: docker/build-push-action@v4
        with:
          context: ./db
          push: true
          no-cache: true
          tags: marioarellano/lixylearning-postgres-db:latest