name: Restrict Branches

on:
  pull_request:
    branches:
      - main

jobs:
  restrict:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "Pull requests to main are only allowed from develop."
          exit 1
